In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [42]:
ruta_dir = os.getcwd()
df=pd.read_parquet(os.path.join(ruta_dir,"..","data","c5_limpio.parquet"))

In [43]:
df.head(10)

,dia_semana,tipo_incidente_c4,incidente_c4,alcaldia_inicio,codigo_cierre,clas_con_f_alarma,tipo_entrada,longitud,latitud,fecha,hora,mes,periodo,fin_semana
0,Miércoles,Accidente,Choque sin lesionados,IZTAPALAPA,1,EMERGENCIA,LLAMADA DEL 066,-99.061040,19.380900,2014-01-01,13,1,medio día,0
1,Miércoles,Accidente,Choque sin lesionados,GUSTAVO A. MADERO,1,EMERGENCIA,LLAMADA DEL 066,-99.103420,19.490530,2014-01-01,21,1,tarde,0
4,Miércoles,Accidente,Choque con lesionados,ALVARO OBREGON,1,URGENCIAS MEDICAS,LLAMADA DEL 066,-99.191040,19.363360,2014-01-01,21,1,tarde,0
5,Miércoles,Accidente,Choque sin lesionados,TLAHUAC,1,EMERGENCIA,LLAMADA DEL 066,-99.054880,19.295440,2014-01-01,19,1,tarde,0
6,Martes,Accidente,Choque con lesionados,AZCAPOTZALCO,1,URGENCIAS MEDICAS,LLAMADA DEL 066,-99.197810,19.482380,2013-12-31,19,12,tarde,0
8,Miércoles,Accidente,Choque con lesionados,COYOACAN,0,URGENCIAS MEDICAS,LLAMADA DEL 066,-99.108050,19.310150,2014-01-01,18,1,tarde,0
9,Miércoles,Accidente,Choque con lesionados,COYOACAN,1,URGENCIAS MEDICAS,BOTÓN DE AUXILIO,-99.144275,19.305041,2014-01-01,16,1,medio día,0
10,Miércoles,Accidente,Choque sin lesionados,ALVARO OBREGON,1,EMERGENCIA,LLAMADA DEL 066,-99.191450,19.363480,2014-01-01,21,1,tarde,0
11,Miércoles,Accidente,Choque sin lesionados,IZTAPALAPA,1,EMERGENCIA,LLAMADA DEL 066,-99.087140,19.304320,2014-01-01,3,1,madrugada,0
13,Miércoles,Accidente,Choque sin lesionados,IZTAPALAPA,1,EMERGENCIA,LLAMADA DEL 066,-99.061040,19.380900,2014-01-01,13,1,medio día,0

In [44]:
df=df.drop(columns=["clas_con_f_alarma","fecha"])

In [48]:
df1=pd.get_dummies(df, columns=["dia_semana","tipo_incidente_c4","incidente_c4","alcaldia_inicio","tipo_entrada","hora","mes","periodo","fin_semana"])

In [49]:
df1

,codigo_cierre,longitud,latitud,dia_semana_Domingo,dia_semana_Jueves,dia_semana_Lunes,dia_semana_Martes,dia_semana_Miércoles,dia_semana_Sábado,dia_semana_Viernes,...,mes_9,mes_10,mes_11,mes_12,periodo_madrugada,periodo_mañana,periodo_medio día,periodo_tarde,fin_semana_0,fin_semana_1
0,1,-99.061040,19.380900,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False
1,1,-99.103420,19.490530,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,True,False
4,1,-99.191040,19.363360,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,True,False
5,1,-99.054880,19.295440,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,True,False
6,1,-99.197810,19.482380,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2115075,1,-99.087270,19.320600,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
2115076,1,-99.125200,19.428723,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
2115077,0,-99.119881,19.380011,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
2115078,0,-99.080981,19.369412,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
2115079,1,-99.054112,19.397305,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False

In [50]:
df1.to_parquet(os.path.join(ruta_dir,"..","data","c5_train_test.parquet"))